- hosts: n-server
  become: yes

  tasks:
    - name: nfs export base directory exists
      file:
        path: /srv
        state: directory

    - name: nfs export directory exists
      file:
        path: /srv/share
        state: directory
        mode: 01777

    - name: nfs exports is configured
      copy:
        content: |
          V4: /srv/share
          /srv/share -network {{ network }} -sec=sys
        dest: /etc/exports
      vars:
        network: "{{ nfs_server | ipsubnet(24, 0) }}"
      notify: restart nfsd

    - name: nfsd service configuration is up
      copy:
        content: |
          nfsv4_server_enable="YES"
          nfs_server_enable="YES"
          nfs_server_flags="-t"
        dest: /etc/rc.conf.d/nfsd
      notify: restart nfsd

    - name: rpcbind service configurations is up
      copy:
        content: |
          rpcbind_enable="YES"
        dest: /etc/rc.conf.d/rpcbind
      notify: restart rpcbind

    - name: mountd service configurations is up
      copy:
        content: |
          mountd_enable="YES"
        dest: /etc/rc.conf.d/mountd
      notify: restart mountd

    - name: nfsd accepts numeric uid
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
      with_items:
        - vfs.nfs.enable_uidtostring
        - vfs.nfsd.enable_stringtouid
      notify: restart nfsd

    - name: nfs server is started
      service:
        name: nfsd
        state: started

  handlers:
    - name: restart nfsd
      service:
        name: nfsd
        state: restarted

    - name: restart rpcbind
      service:
        name: rpcbind
        state: restarted

    - name: restart mountd
      service:
        name: mountd
        state: restarted
