- hosts: rio
  become: yes

  vars:
    k3s_version: v1.18.3+k3s1

  tasks:
    - name: curl is installed
      apt:
        name: curl
        state: present

    - name: k3s is installed
      shell: curl -fsSL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
        warn: no
      environment:
        INSTALL_K3S_VERSION: "{{ k3s_version }}"
        INSTALL_K3S_EXEC: "server --tls-san {{ k3s_address }}"

    - name: k3s remote access config is generated
      shell: |
        sed '/server:/ s/127.0.0.1/{{ k3s_address }}/' /etc/rancher/k3s/k3s.yaml > k3s-remote.yaml
      args:
        warn: no

    - name: k3s access config is downloaded
      fetch:
        src: k3s-remote.yaml
        dest: _k3s.yaml
        flat: yes
