- hosts: nfs
  become: yes

  tasks:
    - name: nfs export directory exists
      file:
        path: /data/nfs/myapp
        state: directory

    - name: nfs exports is configured
      copy:
        content: |
          V4: /data/nfs
          /data/nfs/myapp -network {{ network }} -maproot 0:0
        dest: /etc/exports
      vars:
        network: "{{ nfs_address | ipsubnet(24, 0) }}"
      notify: restart nfsd

    - name: nfsd service configuration is up
      copy:
        content: |
          nfsv4_server_enable="YES"
          nfs_server_enable="YES"
          nfs_server_flags="-t"
        dest: /etc/rc.conf.d/nfsd
      notify: restart nfsd

    - name: nfsd accepts numeric uid
      sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
      with_items:
        - vfs.nfs.enable_uidtostring
        - vfs.nfsd.enable_stringtouid
      notify: restart nfsd

    - name: nfs server is started
      service:
        name: nfsd
        state: started

  handlers:
    - name: restart nfsd
      service:
        name: nfsd
        state: restarted
