- hosts: default
  become: yes

  tasks:
    - name: ipfw script is up
      template:
        src: ipfw.rules.j2
        dest: /etc/ipfw.rules
        mode: 0600
      notify: restart ipfw

    - name: ipfw is enabled
      copy:
        content: |
          firewall_enable="YES"
          firewall_script="/etc/ipfw.rules"
        dest: /etc/rc.conf.d/ipfw
      notify: restart ipfw

    - name: ipfw is started
      service:
        name: ipfw
        state: started

  handlers:
    - name: restart ipfw
      service:
        name: ipfw
        state: restarted
